/*
 * Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause-Clear
 */

#include "supplicant_event_callback.h"

using aidl::android::hardware::wifi::supplicant::SupplicantStatusCode;


uint16_t SupplicantEventArray[SUPPLICANT_EVENT_COUNTS] = {
    /* ISUPPLICANT */
//    SUPPLICANT_ON_INTERFACE_CREATED_IND,
    SUPPLICANT_ON_INTERFACE_REMOVED_IND,

    /* ISUPPLICANTSTAIFACE */
//    SUPPLICANT_STA_IFACE_ON_ANQP_QUERY_DONE_IND,
    SUPPLICANT_STA_IFACE_ON_ASSOCIATION_REJECTED_IND,
    SUPPLICANT_STA_IFACE_ON_AUTHENTICATION_TIMEOUT_IND,
//    SUPPLICANT_STA_IFACE_ON_AUXILIARY_SUPPLICANT_EVENT_IND,
//    SUPPLICANT_STA_IFACE_ON_BSS_TM_HANDLING_DONE_IND,
//    SUPPLICANT_STA_IFACE_ON_BSSID_CHANGED_IND,
    SUPPLICANT_STA_IFACE_ON_DISCONNECTED_IND,
//    SUPPLICANT_STA_IFACE_ON_DPP_FAILURE_IND,
//    SUPPLICANT_STA_IFACE_ON_DPP_PROGRESS_IND,
//    SUPPLICANT_STA_IFACE_ON_DPP_SUCCESS_IND,
//    SUPPLICANT_STA_IFACE_ON_DPP_SUCCESS_CONFIG_RECEIVED_IND,
//    SUPPLICANT_STA_IFACE_ON_DPP_SUCCESS_CONFIG_SENT_IND,
//    SUPPLICANT_STA_IFACE_ON_EAP_FAILURE_IND,
//    SUPPLICANT_STA_IFACE_ON_EXT_RADIO_WORK_START_IND,
//    SUPPLICANT_STA_IFACE_ON_EXT_RADIO_WORK_TIMEOUT_IND,
//    SUPPLICANT_STA_IFACE_ON_HS20_DEAUTH_IMMINENT_NOTICE_IND,
//    SUPPLICANT_STA_IFACE_ON_HS20_ICON_QUERY_DONE_IND,
//    SUPPLICANT_STA_IFACE_ON_HS20_SUBSCRIPTION_REMEDIATION_IND,
    SUPPLICANT_STA_IFACE_ON_HS20_TERMS_AND_CONDITIONS_ACCEPTANCE_REQUESTED_NOTIFICATION_IND,
//    SUPPLICANT_STA_IFACE_ON_NETWORK_ADDED_IND,
    SUPPLICANT_STA_IFACE_ON_NETWORK_NOT_FOUND_IND,
    SUPPLICANT_STA_IFACE_ON_NETWORK_REMOVED_IND,
//    SUPPLICANT_STA_IFACE_ON_PMK_CACHE_ADDED_IND,
//    SUPPLICANT_STA_IFACE_ON_STATE_CHANGED_IND,
//    SUPPLICANT_STA_IFACE_ON_WPS_EVENT_FAIL_IND,
//    SUPPLICANT_STA_IFACE_ON_WPS_EVENT_PBC_OVERLAP_IND,
//    SUPPLICANT_STA_IFACE_ON_WPS_EVENT_SUCCESS_IND,
//    SUPPLICANT_STA_IFACE_ON_QOS_POLICY_RESET_IND,
//    SUPPLICANT_STA_IFACE_ON_QOS_POLICY_REQUEST_IND,
//    SUPPLICANT_STA_IFACE_ON_MLO_LINKS_INFO_CHANGED_IND,
//    SUPPLICANT_STA_IFACE_ON_DPP_CONFIG_RECEIVED_IND,
//    SUPPLICANT_STA_IFACE_ON_DPP_CONNECTION_STATUS_RESULT_SENT_IND,
//    SUPPLICANT_STA_IFACE_ON_BSS_FREQUENCY_CHANGED_IND,
    SUPPLICANT_STA_IFACE_ON_SUPPLICANT_STATE_CHANGED_IND,
//    SUPPLICANT_STA_IFACE_ON_QOS_POLICY_RESPONSE_FOR_SCS_IND,
    SUPPLICANT_STA_IFACE_ON_PMK_SA_CACHE_ADDED_IND,

    /* ISUPPLICANTSTANETWORK */
//    SUPPLICANT_STA_NETWORK_ON_NETWORK_EAP_IDENTITY_REQUEST_IND,
//    SUPPLICANT_STA_NETWORK_ON_NETWORK_EAP_SIM_GSM_AUTH_REQUEST_IND,
//    SUPPLICANT_STA_NETWORK_ON_NETWORK_EAP_SIM_UMTS_AUTH_REQUEST_IND,
    SUPPLICANT_STA_NETWORK_ON_TRANSITION_DISABLE_IND
//    SUPPLICANT_STA_NETWORK_ON_SERVER_CERTIFICATE_AVAILABLE_IND,
//    SUPPLICANT_STA_NETWORK_ON_PERMANENT_ID_REQ_DENIED_IND
};

ndk::ScopedAStatus SupplicantSendEvent(uint16_t eventId, std::vector<uint8_t>& data)
{
    if (!someip_send_event(eventId, data.data(), data.size())) {
        LOG(ERROR) << "Failed to send event ID: " << eventId;
        return ndk::ScopedAStatus::fail(SupplicantStatusCode::FAILURE_UNKNOWN);
    }

    return ndk::ScopedAStatus::ok();
}
